- id: ruff
  name: ruff
  description: "Run 'ruff' for extremely fast Python linting"
  entry: ruff
  language: python
  types_or: [python, pyi]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "0"
