-   id: ruff
    name: ruff
    description: "Run 'ruff' for extremely fast Python linting"
    entry: ruff --force-exclude
    language: python
    'types_or': [python, pyi]
    args: []
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
    stages: [commit, merge-commit, push, manual]
