[project]
name = "ruff-pre-commit"
version = "0.0.0"
dependencies = [
    "ruff==0.8.4",
]

[project.optional-dependencies]
dev = [
    "packaging~=23.1",
    "urllib3>=2.0.5,<3.0.0",
]

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
strict = true
warn_unreachable = true
