name: Releases

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release create "$TAG_NAME" \
            --title "$TAG_NAME" \
            --notes "See: https://github.com/astral-sh/ruff/releases/tag/$TAG_NAME"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
